
POST http://localhost:8080/layer/525a0c95-1971-434b-99e8-ad05c5d12e2d HTTP/1.1
content-type: application/json

[
    {
        "projectNumber": 1,
        "hole": "teste",
        "code": 1,
        "depth": 1,
        "type": "11",
        "description": "AREIA FINA SILTOSA",
        "hatch": "teste"
       
    }
]