
PUT http://localhost:8080/hole/4d61df26-2955-4638-8f4b-2e2fd93635af HTTP/1.1
content-type: application/json

{
    "holeNumber": "string5",
    "initialDate": "2024-08-24",
    "finalDate": "2024-08-24",
    "name": "string",
    "workDescription": "string",
    "quota": "string",
    "waterLevel": 1,
    "interval": "string",
    "waterLevelTwo": 2,
    "intervalTwo": "string",
    "torque": "string",
    "coating": "string",
    "ultimateDigger": "string",
    "initialHelical": "string",
    "finalHelical": "string",
    "printSpt": "string",
    "stop": "string",
    "textPoll": "string",
    "prober": "string",
    "pageLines": "string"
}